data:
  data: QM9_3D
  dir: './data'
  batch_size: 256
  max_node_num: 29
  max_feat_num: 5
  init: atom
  scale: 
    pos: 4.0
    atomtype: 1.0
    charge: 0.1
  include_charge: True

mix:
  atom_feat: # Atom type & Charge
    type: OU
    drift_coeff: 1 
    sigma_0: 1.0
    sigma_1: 0.6
    num_scales: 1000
  pos:
    type: OU
    drift_coeff: 1
    sigma_0: 0.2
    sigma_1: 0.1
    num_scales: 1000

model:
  type: EGNN
  num_layers: 9
  nhid: 256
  time_cond: True

train:
  name: train
  use_tensorboard: False
  num_epochs: 1300
  save_interval: 100
  print_interval: 100
  reduce_mean: False 
  lr: 0.0001
  lr_schedule: False
  ema: 0.999
  weight_decay: 1.0e-12
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 2.0e-4
  optimizer: adamw
  loss_type: 
    atom_feat: scaled
    pos: scaled
  resume: False

sampler:
  predictor: Euler
  corrector: None
  snr: 0.0
  scale_eps: 0.0
  n_steps: 1    

ckpt: QM9_3D

sample:
  n_samples: 10000
  batch_size: 5000
  use_ema: True
  noise_removal: True
  eps: 1.0e-3
  seed: 42