data: 
  data: planar
  batch_size: 128
  max_node_num: 64
  feat:
    type: 
      - eig1
      - eig2
    scale: 10
    norm: True
  perm_mix: True

mix:
  x: 
    type: OU
    drift_coeff: 1
    sigma_0: 0.2
    sigma_1: 0.1
    num_scales: 1000
  adj: 
    type: OU
    drift_coeff: 1 
    sigma_0: 0.4
    sigma_1: 0.2
    num_scales: 1000

model:
  type: transformer
  num_layers: 8
  input_dims:
    E: 2
    y: 0
  hidden_mlp_dims:
    X: 128
    E: 64
    y: 128
  hidden_dims:
    dx: 256
    de: 64
    dy: 64
    n_head: 8
    dim_ffX: 256
    dim_ffE: 64
    dim_ffy: 256
  
train:
  name: test
  use_tensorboard: True
  lambda_train: 5 
  num_epochs: 30000
  save_interval: 2000 
  reduce_mean: False 
  lr: 4.0e-4 
  lr_schedule: False 
  ema: 0.999
  weight_decay: 1.0e-12 
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 2.0e-3 
  optimizer: adamw
  loss_type:
    x: const 
    adj: default

sampler:
  predictor: Euler
  corrector: Langevin
  snr: 0.01
  scale_eps: 0.7
  n_steps: 1

sample:
  batch_size: 40
  use_ema: True 
  eps: 2.0e-3 
  kernel: tv
  noise_removal: True
  seed: 42

ckpt: planar